"""
Generate test_queries.csv — 50+ test queries per intent for NLU evaluation.

Reads menu items from menu_data.json and produces a CSV with columns:
  intent, query, expected_entity, entity_value

Run:  python shared/generate_test_queries.py
Output: shared/test_queries.csv
"""

import csv
import json
import os
import random

random.seed(42)  # reproducible

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MENU_PATH = os.path.join(SCRIPT_DIR, "menu_data.json")
OUTPUT_PATH = os.path.join(SCRIPT_DIR, "test_queries.csv")

# Load menu data
with open(MENU_PATH, "r", encoding="utf-8") as f:
    menu_data = json.load(f)

menu_items = menu_data["menu"]
item_names = [i["name"] for i in menu_items]
spicy_items = [i["name"] for i in menu_items if i["spicy"]]
veg_items = [i["name"] for i in menu_items if i["vegetarian"]]
budget_items = [i["name"] for i in menu_items if i["price"] <= 6.0]

# ---------------------------------------------------------------------------
# Query templates per intent
# ---------------------------------------------------------------------------

QUERIES = {
    "greet": [
        "hi", "hello", "hey there", "selamat pagi", "good morning",
        "what's up", "hiya", "greetings", "yo", "hey", "good afternoon",
        "selamat petang", "hi there", "hello there", "howdy", "good evening",
        "selamat malam", "sup", "hellooo", "hi!", "morning!", "evening!",
        "hey whats up", "helo", "hiiii", "good day", "peace", "how are you",
        "nice to meet you", "assalamualaikum", "hey buddy", "hi friend",
        "hello friend", "greetings!", "salutations", "top of the morning",
        "heyya", "heyya", "ello", "wassup", "yo yo", "hiya!",
        "good night", "how do you do", "pleased to meet you",
        "hey there!", "hello!", "hi!!", "hey!!", "good morning!",
        "good afternoon!", "good evening!", "selamat sejahtera",
        "hi chatbot", "hello robot", "hey smartbite",
    ],
    "goodbye": [
        "bye", "goodbye", "see you", "later", "take care",
        "selamat tinggal", "bye bye", "see ya", "gotta go", "thanks bye",
        "that's all", "nothing else", "done", "exit", "quit",
        "see you later", "catch you later", "im leaving", "good night",
        "bye for now", "see you soon", "farewell", "cya", "ttyl",
        "talk later", "im off", "g2g", "gtg", "peace out",
        "bye have a good day", "thanks goodbye", "ok bye", "alright bye",
        "see you tomorrow", "bye!", "goodbye!", "see ya!",
        "ok that's all thanks", "nothing more bye", "im done",
        "no more questions", "that is all", "bye bye bye",
        "thank you bye", "thanks see you", "ok farewell",
        "bye have a nice day", "take care bye", "see you around",
        "ciao", "adios", "cheerio", "toodles",
    ],
    "menu_browse": [
        "show me the menu", "what do you have", "what's available",
        "what food do you have", "show menu", "tell me the menu",
        "what can I order", "what's on the menu", "list the dishes",
        "browse menu", "see the food", "menu please",
        "what dishes are available", "show me what you sell",
        "what's for sale", "show me the food menu", "show me drinks",
        "do you have desserts", "what appetizers do you have",
        "I want to see the menu", "let me see the menu",
        "can I see the menu", "display the menu", "food menu",
        "what food is available", "what do you serve",
        "what kind of food", "what's your menu", "menu options",
        "food options", "dish options", "what can I eat",
        "show me food", "list all items", "full menu",
        "what's on offer", "today's menu", "specials menu",
        "show me rice dishes", "show me noodles", "show me snacks",
        "show me desserts", "show me beverages", "drinks menu",
        "dessert menu", "snack menu", "rice menu", "noodle menu",
        "appetizer menu", "main course", "side dishes",
        "what Malaysian food do you have", "local food",
        "traditional dishes", "signature dishes menu",
    ],
    "menu_ask_price": [
        "how much is nasi lemak", "price of satay",
        "what's the price of roti canai", "how much does laksa cost",
        "price for mee goreng", "how much for teh tarik",
        "cost of nasi goreng", "what's the price",
        "how much is the curry puff", "pricing for cendol",
        "how much for a drink", "price list",
        "how expensive is the food", "what are the prices",
        "how much should I bring", "how much is chicken rice",
        "price of murtabak", "what does nasi kandar cost",
        "how much for kuih", "how much is char kuey teow",
        "price for pisang goreng", "cost of milo ais",
        "how much is kopi", "price of sirap bandung",
        "how much does air mata kucing cost", "price for ais kacang",
        "how much is pengat", "cost of popiah",
        "how much for nasi dagang", "price of nasi kerabu",
        "how much is nasi ayam", "price for curry mee",
        "how much does mee rebus cost", "tell me the price of satay",
        "what's the cost of nasi lemak", "how much is a roti canai",
        "price of a teh tarik", "how much for one satay",
        "what's the price for laksa", "how much is cendol",
        "tell me prices", "what do things cost",
        "how much money do I need", "budget for food",
        "prices please", "show me prices", "food prices",
        "how much is everything", "what's cheap",
        "cheapest item", "most expensive dish",
    ],
    "order_place": [
        "I want to order", "I'll have nasi lemak", "give me satay",
        "can I order", "I'd like to order", "order mee goreng please",
        "I want nasi goreng", "let me get roti canai",
        "I'll take laksa", "can I get a teh tarik",
        "add satay to my order", "I want to place an order",
        "order for me", "help me order", "I'm ready to order",
        "I want 2 nasi lemak", "give me 3 roti canai",
        "I'll have 1 chicken rice", "order 5 satay",
        "I want nasi kandar and teh tarik",
        "order char kuey teow", "I'd like nasi ayam",
        "add mee rebus to my order", "give me curry mee",
        "I want to order nasi dagang", "order pisang goreng",
        "add popiah to my order", "I'll have curry puff",
        "give me milo ais", "I want kopi",
        "order sirap bandung", "add ais kacang",
        "I want pengat", "give me kuih-muih",
        "order air mata kucing", "I'll have 2 teh tarik",
        "add 3 roti canai to my order", "I want 1 nasi lemak",
        "order 2 char kuey teow", "give me 1 cendol",
        "can I order satay please", "I'd like to order nasi goreng",
        "add nasi kandar to my cart", "I want to buy satay",
        "let me order mee goreng", "I'll order laksa",
        "please add roti canai", "I need 2 nasi lemak",
        "get me 1 teh tarik", "I want some satay",
        "hook me up with nasi goreng", "I'll grab a roti canai",
    ],
    "order_modify": [
        "change to mee goreng", "remove the drink", "add one more satay",
        "modify my order", "switch to nasi kandar", "cancel the laksa",
        "add another roti canai", "change quantity to 2",
        "remove nasi lemak", "update my order",
        "actually I want something else", "change my order",
        "edit order", "modify the quantity",
        "add 3 more satay", "change mee goreng to nasi goreng",
        "remove 2 items", "I want to change the quantity",
        "replace chicken with beef", "update quantity to 4",
        "swap nasi lemak for nasi goreng", "change satay to roti canai",
        "remove the cendol", "add 2 more teh tarik",
        "modify the nasi kandar", "change laksa to curry mee",
        "remove pisang goreng", "add one more nasi lemak",
        "switch from mee goreng to mee rebus",
        "change my drink to milo ais", "update roti canai quantity",
        "remove all drinks", "add extra satay",
        "change the order", "edit my selection",
        "modify item", "switch items", "replace the laksa",
        "change nasi ayam to nasi kandar", "remove one satay",
        "add more roti canai", "update my selection",
        "change quantity of satay", "modify nasi goreng",
        "swap char kuey teow for mee goreng",
        "I changed my mind about the laksa",
        "actually remove the curry puff", "add another teh tarik",
        "change the nasi lemak to nasi dagang",
        "can I change my order", "I want to modify",
    ],
    "order_cancel": [
        "cancel my order", "nevermind", "forget it",
        "cancel everything", "remove all items", "start over",
        "clear my order", "I don't want to order anymore",
        "cancel the whole order", "abort order", "reset order",
        "empty my cart", "discard order", "never mind the order",
        "cancel it", "scrap the order", "I changed my mind",
        "remove my entire order", "forget about the order",
        "cancel all items", "clear everything",
        "I don't want this anymore", "undo my order",
        "delete my order", "wipe my cart", "start fresh",
        "empty the order", "cancel all of it",
        "I want to cancel", "please cancel",
        "never mind cancel", "cancel order please",
        "scratch that", "forget about it", "drop the order",
        "I'll pass on the order", "cancel my selection",
        "remove everything from my order", "clear my cart",
        "I don't want anything", "cancel my food order",
        "abort everything", "reset my order",
        "let's start over", "new order from scratch",
        "cancel and start fresh", "clear all items",
        "I want to start over", "remove all",
        "cancel the entire order", "dump the order",
    ],
    "order_check": [
        "what did I order", "show my order", "current order",
        "what's in my order", "check my order", "view order",
        "order summary", "what have I ordered", "my cart",
        "show cart", "display my order", "order status",
        "what's my order so far", "review my order",
        "see my selections", "how many items in my order",
        "total for my order", "show me what I ordered",
        "what's in my cart", "check cart",
        "what have I selected", "order details",
        "my current order", "list my order",
        "what food did I order", "show order total",
        "how much is my order", "order receipt",
        "what did I add to my order", "review my cart",
        "see my order", "check my cart",
        "what items do I have", "show my selections",
        "order list", "my order so far",
        "did I order anything", "what's on my order",
        "current cart", "cart summary",
        "show me my food", "what did I pick",
        "order overview", "my food order",
        "check what I ordered", "what's my total",
        "show running total", "order progress",
        "am I ordering anything", "what's in the order",
    ],
    "recommend": [
        "what do you recommend", "suggest something",
        "popular dishes", "what's good here", "best dishes",
        "customer favorites", "what should I try", "your recommendation",
        "what's popular", "recommend me something", "best sellers",
        "top picks", "what's your best dish", "chef's recommendation",
        "signature dishes", "what do people usually order",
        "any must-try dishes", "what's the best",
        "recommend a dish", "what's your favorite",
        "what do you suggest", "best food here",
        "most popular item", "what's trending",
        "what should I eat", "give me a recommendation",
        "what's a good dish", "suggest a meal",
        "what's the top dish", "recommend something good",
        "what's your top pick", "best meal here",
        "what's everyone ordering", "hit dish",
        "what's the specialty", "signature dish",
        "what's famous here", "must try food",
        "what's delicious", "recommend me a dish",
        "what's worth trying", "any recommendations",
        "what's the best seller", "crowd favorite",
        "what should I order", "help me choose",
        "pick something for me", "what's hot",
        "popular choice", "staff pick",
    ],
    "recommend_spicy": [
        "something spicy", "I like it hot", "spicy food please",
        "any spicy dishes", "I want something with kick",
        "burn my tongue", "extra spicy", "not too mild",
        "medium spicy", "hot and spicy options",
        "spicy recommendations", "I love chili", "sambal please",
        "pedas", "make it spicy", "I can handle the heat",
        "the hotter the better", "give me the spiciest dish",
        "spiciest food you have", "I want hot food",
        "anything with chili", "fire food",
        "spicy Malaysian food", "really spicy please",
        "I love spicy food", "something with heat",
        "hot dishes", "chili lovers", "spicy noodles",
        "spicy rice", "sambal dishes", "curry options",
        "which dishes are spicy", "show me spicy food",
        "I want something fiery", "hot and spicy",
        "bring the heat", "spicy curry", "spicy sambal",
        "anything pedas", "I want to sweat",
        "make my mouth burn", "spicy options please",
        "hot food recommendations", "spicy picks",
        "I can take the heat", "give me spice",
        "no mild food", "only spicy", "extra hot",
    ],
    "recommend_vegetarian": [
        "vegetarian options", "no meat please", "veggie dishes",
        "I'm vegetarian", "anything without meat",
        "plant-based options", "vegetarian menu",
        "meat-free dishes", "vegan options", "no chicken no beef",
        "just vegetables", "sayur only",
        "vegetarian recommendations", "I don't eat meat",
        "green options", "do you have tofu",
        "any salad options", "show me vegetarian food",
        "what's vegetarian", "veggie food please",
        "no meat dishes", "vegetarian friendly",
        "plant based food", "vegan friendly",
        "meatless options", "vegetarian choices",
        "what can I eat as vegetarian", "I'm vegan",
        "only vegetables please", "non-meat options",
        "veggie picks", "green menu",
        "I don't eat chicken", "no seafood either",
        "pure vegetarian", "vegetable dishes",
        "show me vegan food", "animal-free options",
        "I want vegetables", "meat-free meal",
        "vegetarian food only", "no meat no fish",
        "herbivore options", "plant-based meal",
        "tofu dishes", "veggie friendly",
        "what's meat-free", "vegetarian picks",
        "I eat only vegetables", "green dishes",
    ],
    "recommend_budget": [
        "something cheap", "budget meal", "under RM10",
        "affordable options", "value meals", "cheap and good",
        "budget-friendly", "low price", "economical",
        "student budget", "save money", "cheapest options",
        "bang for buck", "under RM5", "not expensive",
        "affordable food", "what's cheap",
        "budget friendly dishes", "low cost food",
        "cheap food please", "I'm on a budget",
        "inexpensive options", "what can I get cheap",
        "cheapest dish", "most affordable",
        "student meal", "wallet-friendly",
        "I don't have much money", "cheap eats",
        "value for money", "budget options",
        "affordable meal", "what's affordable",
        "low budget food", "economic meal",
        "cheap Malaysian food", "under RM8",
        "budget recommendations", "dirt cheap",
        "I'm broke", "penny pinching",
        "save some money", "cheap picks",
        "affordable picks", "budget eats",
        "what's the cheapest", "lowest price",
        "student friendly", "value picks",
        "cheap options", "I want something affordable",
    ],
    "dietary_info": [
        "is it halal", "any gluten-free options", "allergens",
        "is nasi lemak halal", "do you have vegetarian food",
        "what contains nuts", "is there dairy",
        "food allergies", "ingredients list", "nutritional info",
        "is this spicy", "contains pork?",
        "halal certified", "allergy information",
        "dietary restrictions", "does laksa contain shellfish",
        "is roti canai vegan", "what's in nasi goreng",
        "is the food halal", "any allergy info",
        "what allergens are in the food", "nutritional information",
        "is there gluten", "does it contain eggs",
        "is satay halal", "what ingredients",
        "food safety info", "is cendol vegan",
        "does curry mee have shellfish", "allergy warnings",
        "is there MSG", "is the chicken halal",
        "what's in the sambal", "does it contain peanuts",
        "is there coconut milk", "dairy-free options",
        "nut-free options", "is mee goreng vegetarian",
        "ingredient list", "dietary needs",
        "food composition", "what's in laksa",
        "is kopi vegan", "does teh tarik have dairy",
        "is popiah vegan", "allergen information",
        "is pisang goreng gluten-free", "halal status",
        "food allergies info", "dietary requirements",
    ],
    "complaint_food": [
        "food is cold", "wrong order", "tastes bad",
        "this is not what I ordered", "the food is terrible",
        "nasi lemak is bland", "sambal too spicy",
        "food is stale", "undercooked", "overcooked",
        "hair in my food", "food quality is poor",
        "this tastes weird", "not fresh", "bad taste",
        "the satay is burnt", "roti canai is too oily",
        "this food is disgusting", "the rice is hard",
        "laksa is too salty", "the chicken is raw",
        "my food is cold", "this doesn't taste right",
        "the noodles are soggy", "food is overcooked",
        "there's something in my food", "the curry is watered down",
        "this is inedible", "worst food ever",
        "food is not good", "bad quality food",
        "the dish is cold", "my order is wrong",
        "this is not fresh", "the food stinks",
        "terrible taste", "food poisoning",
        "the dessert is too sweet", "drinks are flat",
        "the kopi is cold", "satay is dry",
        "nasi goreng is bland", "char kuey teow is greasy",
        "curry mee is tasteless", "mee rebus is too sweet",
        "the food is old", "reheated food",
        "not what I expected", "disappointed with food",
        "food complaint", "bad food",
    ],
    "complaint_service": [
        "waiting too long", "slow service", "been waiting 30 minutes",
        "where is my food", "service is terrible",
        "nobody is attending", "long wait", "too slow",
        "hurry up", "when will my food arrive", "still waiting",
        "took forever", "staff is rude", "poor service",
        "no one came", "I've been waiting for ages",
        "the service here is unacceptable",
        "I've been waiting too long", "no one is serving me",
        "where is the waiter", "service is very slow",
        "this is taking forever", "I need attention",
        "can someone take my order", "nobody cares",
        "ignored by staff", "waiter is rude",
        "very bad service", "slowest service ever",
        "my food hasn't arrived", "waiting for 20 minutes",
        "where's my order", "still no food",
        "service complaint", "bad service",
        "staff ignoring me", "no service at all",
        "when will someone come", "I need help",
        "flag someone down", "call the manager",
        "worst service", "unacceptable wait",
        "this is ridiculous", "I'm frustrated",
        "service is unacceptable", "very slow service",
        "waited too long", "food is late",
        "no one is here", "empty restaurant no service",
    ],
    "complaint_other": [
        "dirty table", "rude staff", "restaurant is dirty",
        "bathroom is filthy", "too noisy", "uncomfortable seats",
        "noisy environment", "bad experience", "not coming back",
        "terrible place", "overpriced", "not worth the money",
        "broken chair", "hot inside", "no air conditioning",
        "the floor is sticky", "mosquitoes everywhere",
        "the restaurant smells", "too crowded",
        "music is too loud", "tables are dirty",
        "noisy customers", "the AC is not working",
        "it's too hot", "the place is a mess",
        "unhygienic", "cockroach on the wall",
        "flies everywhere", "dirty utensils",
        "the plate is dirty", "water is leaking",
        "parking is terrible", "hard to find",
        "overpriced for the quality", "not worth it",
        "bad atmosphere", "too cramped",
        "uncomfortable seating", "the place is rundown",
        "needs renovation", "dirty restroom",
        "bathroom needs cleaning", "the chair is broken",
        "no ventilation", "smells bad",
        "environment is bad", "not clean",
        "health hazard", "report to health department",
        "the place is disgusting", "never coming back",
    ],
    "ask_hours": [
        "when are you open", "what time do you close",
        "operating hours", "business hours", "open until what time",
        "what time open", "closing time", "are you open now",
        "open today?", "weekend hours", "holiday hours",
        "breakfast hours", "lunch hours", "dinner hours",
        "last order time", "are you open on weekends",
        "what time does lunch start", "do you open early",
        "what are your hours", "opening time",
        "when do you close", "are you open at night",
        "do you serve breakfast", "what time is last order",
        "are you open on public holidays", "what time do you open",
        "morning hours", "evening hours", "late night",
        "do you close for lunch", "hours of operation",
        "what time are you open until", "when does the kitchen close",
        "are you open 24 hours", "what days are you open",
        "do you open on Sunday", "Saturday hours",
        "weekday hours", "what time can I come",
        "when should I visit", "best time to come",
        "are you open now?", "what time does dinner start",
        "do you serve supper", "tea time hours",
        "snack time", "when is peak hour",
        "is it busy now", "what's the best time to visit",
    ],
    "ask_location": [
        "where are you", "address", "how to get there",
        "location", "directions", "where is the restaurant",
        "are you in KL", "which area", "GPS location",
        "landmark near you", "near TARUMT?", "how to find you",
        "your address", "map", "Waze link",
        "are you near KLCC", "which street are you on",
        "are you in Setapak", "where exactly are you",
        "how do I get there", "what's your address",
        "directions please", "where is this place",
        "nearby landmarks", "how far are you",
        "are you easy to find", "is there parking",
        "where can I park", "which floor",
        "near which train station", "bus route",
        "how to go there", "send me the location",
        "Google Maps link", "what area are you in",
        "are you in the city center", "suburb location",
        "exact address", "building name",
        "which building", "ground floor?",
        "near the main entrance", "location details",
        "how to reach you", "where is SmartBite",
        "give me directions", "I'm lost",
        "help me find you", "where is Warung SmartBite",
        "Setapak area", "TARUMT campus",
    ],
    "ask_reservation": [
        "book a table", "reserve for 4", "I want to make a reservation",
        "table for 2", "can I book", "reservation for tonight",
        "reserve a seat", "do you take reservations",
        "booking", "table reservation", "reserve for 6 people",
        "large group booking", "VIP room available?",
        "private dining", "walk-in ok?", "table for 8 please",
        "can I book a private room",
        "reservation for tomorrow night",
        "I want to reserve", "can I make a booking",
        "table for 10", "group reservation",
        "do I need to book", "reservation for Friday",
        "book for tonight", "reserve a table for 3",
        "can I get a table", "is booking required",
        "do you accept walk-ins", "VIP room booking",
        "private room available", "book for tomorrow",
        "reservation for this weekend", "table for 5",
        "large group coming", "party of 12",
        "birthday reservation", "celebration booking",
        "anniversary dinner booking", "corporate booking",
        "function room", "event booking",
        "can we book for 20 people", "is there a private area",
        "reserve for dinner", "lunch reservation",
        "breakfast booking", "reserve for this evening",
        "book a spot", "I need a table",
    ],
    "ask_payment": [
        "do you accept card", "payment methods",
        "can I pay by touch n go", "cash only?",
        "accept grabpay", "credit card accepted?",
        "how to pay", "e-wallet ok?", "QR payment",
        "pay wave", "debit card", "online payment",
        "installment", "split bill", "payment options",
        "can I use boost", "do you take fpx",
        "can we split the bill", "what payment methods",
        "can I pay by card", "is cash accepted",
        "can I use e-wallet", "QR pay ok?",
        "do you accept Maybank QR", "can I use ShopeePay",
        "payment by app", "can I pay later",
        "installment plan", "pay at counter?",
        "bill splitting", "how do I pay",
        "what forms of payment", "can I use my phone to pay",
        "digital payment", "mobile payment",
        "contactless payment", "NFC payment",
        "can I pay with Grab", "TouchNGo accepted?",
        "can I use BigPay", "online banking ok?",
        "bank transfer", "can I pay by QR",
        "payment method", "how to settle the bill",
        "bill please", "check please",
        "can I pay now", "I want to pay",
        "ready to pay", "settle the bill",
    ],
    "thanks": [
        "thank you", "thanks a lot", "appreciate it",
        "thanks for the help", "terima kasih",
        "thank you so much", "thanks dear", "cheers",
        "much appreciated", "tq", "thx", "ty",
        "thanks for your help", "really helpful",
        "thanks buddy", "that's very helpful",
        "thanks for the info", "thanks so much",
        "thank you very much", "many thanks",
        "thanks a bunch", "you're the best",
        "that's great thanks", "perfect thanks",
        "awesome thanks", "wonderful thanks",
        "that helps a lot", "you've been helpful",
        "I appreciate your help", "thanks for everything",
        "thanks for the recommendation", "thanks for the suggestion",
        "thank you for the food", "thanks for the menu",
        "thanks for the info", "that's all I needed",
        "you've been great", "very helpful thank you",
        "thanks for your time", "I'm grateful",
        "thank you for your help", "thanks that's perfect",
        "exactly what I needed thanks", "great help thanks",
        "thanks!", "thank you!", "thx!",
        "ty!", "tq!", "awesome!",
    ],
}

# ---------------------------------------------------------------------------
# Generate CSV
# ---------------------------------------------------------------------------

rows = []
for intent, queries in QUERIES.items():
    for q in queries:
        rows.append({
            "intent": intent,
            "query": q.strip(),
            "expected_entity": "",
            "entity_value": "",
        })

# Shuffle for realism
random.shuffle(rows)

# Write CSV
with open(OUTPUT_PATH, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["intent", "query", "expected_entity", "entity_value"])
    writer.writeheader()
    writer.writerows(rows)

print(f"Generated {len(rows)} test queries across {len(QUERIES)} intents")
print(f"Output: {OUTPUT_PATH}")

# Print summary per intent
for intent, queries in sorted(QUERIES.items()):
    print(f"  {intent}: {len(queries)} queries")
